Hw04 lru cache
Gilfoyle3301/hw_golang pull request #4
Opened 2024-03-23 18:22 UTC by Gilfoyle3301

## Домашнее задание №4 «LRU-кэш»

### Чек-лист студента ([Что это?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0))
- [ ] Я перечитал задание после решения. [Зачем перечитывать задание?](https://github.com/OtusGolang/home_work/wiki/%D0%9A%D0%BE%D0%BC%D0%BC%D0%B5%D0%BD%D1%82%D0%B0%D1%80%D0%B8%D0%B8-%D0%BA-%D1%87%D0%B5%D0%BA-%D0%BB%D0%B8%D1%81%D1%82%D1%83-%D1%81%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0#user-content-%D0%97%D0%B0%D1%87%D0%B5%D0%BC-%D0%BF%D0%B5%D1%80%D0%B5%D1%87%D0%B8%D1%82%D1%8B%D0%B2%D0%B0%D1%82%D1%8C-%D0%B7%D0%B0%D0%B4%D0%B0%D0%BD%D0%B8%D0%B5)
- [ ] Я запустил `go mod tidy`.
- [ ] Я удалил `.sync` файл. [Зачем его удалять?](https://github.com/OtusGolang/home_work/wiki/%5B%D0%A1%D1%82%D1%83%D0%B4%D0%B5%D0%BD%D1%82%D0%B0%D0%BC%5D-%D0%9F%D1%80%D0%BE%D1%86%D0%B5%D1%81%D1%81-%D1%81%D0%B4%D0%B0%D1%87%D0%B8-%D0%94%D0%97#user-content-%D0%92%D0%B0%D1%80%D0%B8%D0%B0%D0%BD%D1%82-2)
- [ ] Я проверил, что все операции выполняются за О(1).

### Критерии оценки
- [ ] Пайплайн зелёный - 4 балла
- [ ] Добавлены новые юнит-тесты для списка - 1 балл
- [ ] Добавлены новые юнит-тесты для кэша (включая тест на логику
выталкивания из кэша редко используемых элементов) - до 3 баллов
- [ ] Понятность и чистота кода - до 2 баллов

#### Зачёт от 7 баллов

2024-03-29 16:19 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +		}
тут можно заменить на операцию со слайсами

2024-03-29 16:20 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +		forSort[v] = counts + 1
равнозначно forSort[v]++

2024-03-29 16:20 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +	}
тут не o(1)

2024-03-29 16:21 UTC, ityulkanov commented on hw04_lru_cache/cache.go
> +	}
необходимо поправить

2024-03-29 16:22 UTC, ityulkanov commented on hw04_lru_cache/cache_test.go
>  		require.False(t, ok)
добавьте пожалуйста парочку тестов кеша самого

2024-03-29 16:24 UTC, ityulkanov commented on hw04_lru_cache/cache_new_test.go
а чем не подошёл старый файл?

2024-03-29 16:37 UTC, ityulkanov requested changes
Добрый день, необходимо поправить метод getKey чтобы поиск проходил за o(1), как указано в условии. как поправите, приму.

2024-03-30 09:11 UTC, Gilfoyle3301 commented on hw03_frequency_analysis/top.go
> +		forSort[v] = counts + 1
Не совсем понял, в чем равнозначность?

2024-03-31 08:34 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +		forSort[v] = counts + 1
```suggestion
		forSort[v]++
```

2024-03-31 08:34 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +		forSort[v] = counts + 1
Поправил, надеюсь так понятнее будет

2024-04-09 18:50 UTC, Gilfoyle3301 commented on hw04_lru_cache/cache_new_test.go
разделил тесты для удобства

2024-04-09 18:57 UTC, Gilfoyle3301 commented on hw04_lru_cache/cache.go
> +	}
Исправлено

2024-04-09 18:57 UTC, Gilfoyle3301 commented on hw03_frequency_analysis/top.go
> +		forSort[v] = counts + 1
Исправлено

2024-04-13 07:50 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
Удалите, пожалуйста лишние файлы из PR

2024-04-16 20:35 UTC, ityulkanov commented on hw03_frequency_analysis/top.go
> +		forSort[v] = counts + 1
А вы правки в этом PR сделали или в каком то другом? Не вижу изменений

2024-04-22 15:05 UTC, engineer-go approved these changes

2024-05-07 15:42 UTC, merged